site_name: Hello World

theme:
  name: "material"

plugins:
- mkdocstrings: 
    handlers:
      python:
        paths: [src/swd3_hypot]  # search packages in the src folder

nav:
  - Main page: index.md
  - second page: docs/index.md